# Build settings
# Gems
gems:
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"
url: "http://maxmilian.github.io/ntu_specs_law"
enforce_ssl: ""
baseurl: "/ntu_specs_law"

# Title of website
title: 台大法律學分班27C

#Default keywords (used if no keywords are specified on a page basis)
keywords: 法律學分班, 台大, etc

# Short description of your site
desc: 台大法律學分班錄音檔整理

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
  Home: ""
  About: "about"
  Contact: "contact"

# --- Footer options --- #

# If the values are empty, they are ignored
profile:
  name: Hsu, MingHung
  email: maxmilian@gmail.com
  github: maxmilian

# To display link in the footer section
pretty-url: "maxmilian.github.io/ntu_specs_law/"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: "Your-Disqus-Id"

# Google Analytics Settings
google_analytics: "Your-GA-Id"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Asia/Taipei"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Hsu, MingNung
creator-url: https://github.com/maxmilian
