# Build settings
# Gems
gems:
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
url: "http://maxmilian.github.io/ntu_specs_law"
enforce_ssl: ""
baseurl: "/ntu_specs_law"
file_semester1: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester1"

civil_procedure_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester2/civil_procedure/records"
civil_procedure_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester2/civil_procedure/ra_records"

criminal_procedure_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester2/criminal_procedure/records"
criminal_procedure_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester2/criminal_procedure/ra_records"

enforcement_act_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/enforcement_act/records"
enforcement_act_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/enforcement_act/ra_records"

enforcement_act_record_2016h2: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/enforcement_act_2016h2/records"
enforcement_act_ra_record_2016h2: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/enforcement_act_2016h2/ra_records"

intellectual_property_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/intellectual_property/records"
intellectual_property_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/intellectual_property/ra_records"

intellectual_property_record_2016h2: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/intellectual_property_2016h2/records"
intellectual_property_ra_record_2016h2: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/elective/intellectual_property_2016h2/ra_records"

insurance_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/insurance/records"
insurance_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/insurance/ra_records"

company_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/company/records"
company_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/company/ra_records"

adminitrative_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/adminitrative/records"
adminitrative_ra_record: "https://s3-ap-northeast-1.amazonaws.com/maxmilian-ntu-specs-law/semester3/adminitrative/ra_records"


encoding: utf-8

# Title of website
title: 台大法律學分班27C

#Default keywords (used if no keywords are specified on a page basis)
keywords: 法律學分班, 台大, etc

# Short description of your site
desc: 台大法律學分班錄音檔整理


# List of links in the navigation bar
nav-links:
  第三學期: "semester3"
  選修: "elective"
  上傳說明: "upload"
  Contact: "contact"

# --- Misc --- #

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

created-by: Max Hsu
creator-url: https://github.com/maxmilian
